2018-12-31 10:02:01 DEBUG - hello debug,{} (com.znv.peim.test.LogTest.main:13) [main:5819]
2018-12-31 10:02:01  INFO - hello info,{} (com.znv.peim.test.LogTest.main:14) [main:5821]
2018-12-31 10:02:01 ERROR - hello error,{} (com.znv.peim.test.LogTest.main:15) [main:5822]
2018-12-31 10:05:15 DEBUG - Using custom jdbc url: jdbc:mysql://10.45.157.49:3306/usmsc?useSSL=false&rewriteBatchedStatements=true (com.znv.data.dao.ConfigTranslator.getConfigByProperties:165) [main:4969]
2018-12-31 10:05:15 DEBUG - Using custom jdbc url: jdbc:mysql://10.45.157.49:3306/usmschis?useSSL=false&rewriteBatchedStatements=true (com.znv.data.dao.ConfigTranslator.getConfigByProperties:165) [main:4979]
2018-12-31 10:05:15  INFO - Database 'ZNVDB' use connection pool (com.znv.data.dao.DataSourceBuilder.buildDataSource:65) [main:4984]
2018-12-31 10:05:15 DEBUG - Database 'ZNVDB' minimum-connections:10 (com.znv.data.dao.DataSourceBuilder.buildDataSource:108) [main:4994]
2018-12-31 10:05:15 DEBUG - Database 'ZNVDB' maximum-connections:50 (com.znv.data.dao.DataSourceBuilder.buildDataSource:109) [main:4994]
2018-12-31 10:05:15 DEBUG - Database 'ZNVDB' prototype-count:5 (com.znv.data.dao.DataSourceBuilder.buildDataSource:110) [main:4994]
2018-12-31 10:05:15 DEBUG - Database 'ZNVDB' maximum-active-time:300000 mills (com.znv.data.dao.DataSourceBuilder.buildDataSource:111) [main:4995]
2018-12-31 10:05:15 DEBUG - Database 'ZNVDB' maximum-connection-lifetime:18000000 mills (com.znv.data.dao.DataSourceBuilder.buildDataSource:112) [main:4996]
2018-12-31 10:05:15  INFO - Init database 'ZNVDB' successfully (com.znv.data.dao.DatabaseFactory.initDB:143) [main:5254]
2018-12-31 10:05:15  INFO - Database 'HISDB' use connection pool (com.znv.data.dao.DataSourceBuilder.buildDataSource:65) [main:5258]
2018-12-31 10:05:15 DEBUG - Database 'HISDB' minimum-connections:10 (com.znv.data.dao.DataSourceBuilder.buildDataSource:108) [main:5264]
2018-12-31 10:05:15 DEBUG - Database 'HISDB' maximum-connections:50 (com.znv.data.dao.DataSourceBuilder.buildDataSource:109) [main:5264]
2018-12-31 10:05:15 DEBUG - Database 'HISDB' prototype-count:5 (com.znv.data.dao.DataSourceBuilder.buildDataSource:110) [main:5264]
2018-12-31 10:05:15 DEBUG - Database 'HISDB' maximum-active-time:300000 mills (com.znv.data.dao.DataSourceBuilder.buildDataSource:111) [main:5265]
2018-12-31 10:05:15 DEBUG - Database 'HISDB' maximum-connection-lifetime:18000000 mills (com.znv.data.dao.DataSourceBuilder.buildDataSource:112) [main:5265]
2018-12-31 10:05:15  INFO - Init database 'HISDB' successfully (com.znv.data.dao.DatabaseFactory.initDB:143) [main:5268]
2018-12-31 10:05:15  INFO - 2 databases config success (com.znv.data.dao.DatabaseFactory.initDB:149) [main:5268]
2018-12-31 10:05:17 ERROR - Table 'usmschis.t_zxm_metedatahist' doesn't exist (com.znv.data.dao.Database.executeNonQuery:355) [main:7474]
2019-01-02 09:17:49 DEBUG - Connecting to 10.45.157.66:8000 (com.znv.net.tcp.TcpManager.connect:350) [main:10521]
2019-01-02 09:17:49 DEBUG - TcpManager initializing (com.znv.net.tcp.TcpManager.init:632) [main:10527]
2019-01-02 09:17:49 DEBUG - Heart beat thread enter (com.znv.net.tcp.HeartBeatThread.run:36) [Heart Beat Thread:10679]
2019-01-02 09:17:50 DEBUG - ClientSocket 10.45.149.8:51331 -> 10.45.157.66: 8000 connected (com.znv.net.tcp.ClientSocket.processConnectSuccessFuture:293) [main:11080]
2019-01-02 09:17:50 DEBUG - onConnected: 10.45.157.66:8000  (com.znv.net.siptcp.comm.SocketEvent.onConnected:61) [main:11494]
2019-01-02 09:17:50 DEBUG - proxy connected. (com.znv.scop.proxy.factory.AbstractModule.onConnected:108) [main:11499]
2019-01-02 09:18:32 DEBUG - LogTest.class (com.znv.peim.test.SipTest.RegistCommand:129) [main:53387]
2019-01-02 09:18:32 DEBUG - RedisCapability.class (com.znv.peim.test.SipTest.RegistCommand:129) [main:53563]
2019-01-02 09:18:32 DEBUG - SipTest.class (com.znv.peim.test.SipTest.RegistCommand:129) [main:53564]
2019-01-02 09:18:32 DEBUG - Slf4jTest.class (com.znv.peim.test.SipTest.RegistCommand:129) [main:53566]
